### ISSUE TITLE
New Database SQL files required

### ISSUE THREAD

**Issue by IvandaNothabeer** [Fijo/EVE-Composition-Planer#11]
I'm having serious issues getting the program to run due to multiple problems with the MySQL database table structures.

Around 50% of the save commands in various functions are failing because of invalid column defaults, constraints, timestamp defaults etc. (e.g. User table has the "recover_password_code" field set to NOT NULL DEFAULT NONE but the sql save does not try to set the field, leading to an INSERT failure. The gr0up table has an invalid configuration of lastModified and lastCompleted defaults )

I'm not sure whats going on here, but it isnt good.

**Comment by Fijo** [comment]
Sounds like the issue is your mysql server configuration.
The way I'm working with my database is not according to the strict mode to mysql.
This is why I haven't had to set default values for many fields.
This seems to be no issue if you turn off the strict mode in your mysql server configuration.

Edit the config file "/etc/mysql/my.cnf" with your texteditor.
search for
sql_mode
if you find a line with that put a # in from of it coment out the line.

Under the [mysqld] section look for innodb_strict_mode.
If you find a line where its set change it so it matches the folowing line if you dont just add this one.
innodb_strict_mode             = 0

I hope this solves your problems.
You might have to recreate your database after that I'm not sure I've never had that specific issue myself.
Sorry for the late feedback and good luck!

**Comment by IvandaNothabeer** [comment]
I fixed this by changing the table structure and removing the NOT NULL restriction from each field. I also had to make some adjustments to the default datetime field values (which would also explain why you might still be having issues with the datime updates).

I can probably upload an updated SQL fole of you wish.

**Comment by Fijo** [comment]
yes that would be amazing while I can use SQL to do most things for me I'm still not really the best in it. I'm more focused on the actual algorithms for the program. I apologize for the issue
